# cows and bulls is a type of a code breaker game, where a 4 digit number is being randomly generated by computer, and the user has to guess the number. 
# bulls means that the number you guessed is correct and at correct position, cow means that the number you guessed is correct but not at correct position.
# Note : the numbers shouldn't be repeated  

import random

# returns list of digits of numbers
def getDigits(num):
    return [int(i) for i in str(num)]

# returns true if number has no duplicate digits, otherwise false
def noDuplicate(num):
    num_li = getDigits(num)
    if(len(num_li) == len(set(num_li))):
        return True
    else:
        return False

# generates 4 digit number with no repeated digits
def generateNum():
    while True:
        num = random.randint(1000,9999)
        if noDuplicate(num):
            return num

# returns common digits in correct position ( bulls ), common digits in wrong position ( cows )
def numOfBullsCows(num, guess):
    bull_cow = [0,0]
    num_li = getDigits(num)
    guess_li = getDigits(guess)
    for i,j in zip(num_li, guess_li):
        # common digits present
        if j in num_li:
            # common digits in correct position
            if j==i:
                bull_cow[0]+=1
            # common digits in wrong position
            else:
                bull_cow[1]+=1
    return bull_cow

# secret code
num = generateNum()
tries = int(input("enter no. of tries sufficient for you to guess the number : "))

while tries>0:
    guess = int(input("enter your guess : "))
    if not noDuplicate(guess):
        print("number shouldn't have repeated digits ")
        continue
    if guess<1000 or guess>9999:
        print("please enter 4 digit number only!")
        continue

    bull_cow = numOfBullsCows(num, guess)
    print(f"{bull_cow[0]} bulls , {bull_cow[1]} cows ")
    tries -= 1

    # all 4 digits are bull, i.e all correct digits at correct position 
    if bull_cow[0]==4:
        print(f"You guessed the correct number!! with {tries} guesses left")
        break
else:
    print(f"You ran out of tries. Number was {num}")